# Generated by Django 4.0.3 on 2022-04-20 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FigureOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_trees_planted', models.IntegerField()),
                ('total_species', models.IntegerField()),
                ('total_hectares', models.FloatField()),
            ],
        ),
    ]
