# Generated by Django 4.0.3 on 2022-04-18 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division_name', models.CharField(max_length=100)),
                ('division_img', models.ImageField(null=True, upload_to='division_img/', verbose_name='Division')),
            ],
        ),
        migrations.CreateModel(
            name='FigureOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_input', models.DateTimeField(auto_now_add=True)),
                ('total_trees_planted', models.IntegerField()),
                ('total_species', models.IntegerField()),
                ('total_hectares', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PlantingFigure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_input', models.DateTimeField(auto_now_add=True)),
                ('date_planted', models.CharField(max_length=50)),
                ('planting_program_name', models.CharField(max_length=200)),
                ('planting_total_trees_planted', models.IntegerField()),
                ('planting_species', models.TextField()),
                ('planting_number_of_species', models.IntegerField()),
                ('planting_total_hectares', models.FloatField()),
                ('planting_location', models.CharField(max_length=250)),
                ('planting_division', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='figure.division')),
            ],
            options={
                'ordering': ['-planting_total_trees_planted'],
            },
        ),
        migrations.CreateModel(
            name='FigureByDivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('figure_division_total', models.IntegerField()),
                ('figure_division', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='figure.division')),
            ],
            options={
                'ordering': ['-figure_division_total'],
            },
        ),
    ]
