# Generated by Django 4.0.3 on 2022-04-20 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('figure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FigureByDivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division_name', models.CharField(choices=[('KUCHING', 'Kuching'), ('SRI AMAN', 'Sri Aman'), ('SARIKEI', 'Sarikei'), ('KAPIT', 'Kapit'), ('SIBU', 'Sibu'), ('BINTULU', 'Bintulu'), ('MIRI', 'Miri'), ('LAWAS', 'Lawas')], default='KUCHING', max_length=20)),
                ('division_total_trees', models.IntegerField()),
            ],
        ),
    ]
