# Generated by Django 4.0.3 on 2022-04-12 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('figure', '0002_alter_division_division_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='FigureByDivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division_total_trees_planted', models.IntegerField()),
                ('figure_division', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='figure.division')),
            ],
            options={
                'ordering': ['-division_total_trees_planted'],
            },
        ),
    ]
