# Generated by Django 4.0.3 on 2022-04-20 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('figure', '0002_figurebydivision'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantingFigure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_input', models.DateTimeField(auto_now_add=True)),
                ('date_planted', models.CharField(max_length=50)),
                ('planting_program_name', models.CharField(max_length=200)),
                ('planting_division', models.CharField(choices=[('KUCHING', 'Kuching'), ('SRI AMAN', 'Sri Aman'), ('SARIKEI', 'Sarikei'), ('KAPIT', 'Kapit'), ('SIBU', 'Sibu'), ('BINTULU', 'Bintulu'), ('MIRI', 'Miri'), ('LIMBANG', 'Limbang'), ('LAWAS', 'Lawas')], default='KUCHING', max_length=20)),
                ('planting_total_trees_planted', models.IntegerField()),
                ('planting_species', models.TextField()),
                ('planting_number_of_species', models.IntegerField()),
                ('planting_total_hectares', models.FloatField()),
                ('planting_location', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ['-planting_total_trees_planted'],
            },
        ),
        migrations.AlterModelOptions(
            name='figurebydivision',
            options={'ordering': ['-division_total_trees']},
        ),
        migrations.AlterField(
            model_name='figurebydivision',
            name='division_name',
            field=models.CharField(choices=[('KUCHING', 'Kuching'), ('SRI AMAN', 'Sri Aman'), ('SARIKEI', 'Sarikei'), ('KAPIT', 'Kapit'), ('SIBU', 'Sibu'), ('BINTULU', 'Bintulu'), ('MIRI', 'Miri'), ('LIMBANG', 'Limbang'), ('LAWAS', 'Lawas')], default='KUCHING', max_length=20),
        ),
    ]
