# Generated by Django 4.0.3 on 2022-04-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('figure', '0003_plantingfigure_alter_figurebydivision_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='figurebydivision',
            name='division_description',
            field=models.TextField(null=True),
        ),
    ]
