# Generated by Django 4.0.3 on 2022-04-12 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('figure', '0003_figurebydivision'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FigureByDivision',
        ),
    ]
