# Generated by Django 4.0.3 on 2022-04-20 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('figure', '0004_figurebydivision_division_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='figurebydivision',
            name='division_img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
