# Generated by Django 4.0.3 on 2022-04-21 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('figure', '0005_figurebydivision_division_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plantingfigure',
            options={'ordering': ['-year', '-month']},
        ),
        migrations.RemoveField(
            model_name='plantingfigure',
            name='date_planted',
        ),
        migrations.AddField(
            model_name='plantingfigure',
            name='day',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='plantingfigure',
            name='month',
            field=models.CharField(choices=[('JANUARY', 'January'), ('FEBRUARY', 'February'), ('MARCH', 'March'), ('APRIL', 'April'), ('MAY', 'May'), ('JUNE', 'June'), ('JULY', 'July'), ('AUGUST', 'August'), ('SEPTEMBER', 'September'), ('OCTOBER', 'October'), ('NOVEMBER', 'November'), ('DISEMBER', 'Disember')], default='January', max_length=15),
        ),
        migrations.AddField(
            model_name='plantingfigure',
            name='year',
            field=models.CharField(choices=[('2025', '2025'), ('2024', '2024'), ('2023', '2023'), ('2022', '2022'), ('2021', '2021'), ('2020', '2020'), ('2019', '2019')], default='2022', max_length=10),
        ),
        migrations.AlterField(
            model_name='figurebydivision',
            name='division_img',
            field=models.ImageField(null=True, upload_to='division_img/', verbose_name='Division Image'),
        ),
    ]
