# Generated by Django 4.0.3 on 2022-04-22 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('figure', '0006_alter_plantingfigure_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plantingfigure',
            options={'ordering': ['-date_input']},
        ),
        migrations.AddField(
            model_name='plantingfigure',
            name='date_planted',
            field=models.DateField(auto_now=True),
        ),
    ]
