# Generated by Django 4.0.3 on 2022-04-28 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('figure', '0007_alter_plantingfigure_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantingfigure',
            name='date_planted',
        ),
        migrations.AlterField(
            model_name='plantingfigure',
            name='year',
            field=models.CharField(choices=[('2025', '2025'), ('2024', '2024'), ('2023', '2023'), ('2022', '2022'), ('2021', '2021')], default='2022', max_length=10),
        ),
    ]
